import 'dotenv/config';

import { db } from '~/server/db';
import { ingredients } from '~/server/db/schema';

const data = [
  { name: 'Víz' },

  // Zöldségek
  { name: 'Vöröshagyma' },
  { name: 'Fokhagyma' },
  { name: 'Paradicsom' },
  { name: 'Paprika' },
  { name: 'Chili' },
  { name: 'Sárgarépa' },
  { name: 'Fehérrépa' },
  { name: 'Burgonya' },
  { name: 'Édesburgonya' },
  { name: 'Uborka' },
  { name: 'Cukkini' },
  { name: 'Padlizsán' },
  { name: 'Brokkoli' },
  { name: 'Karfiol' },
  { name: 'Spenót' },
  { name: 'Káposzta' },
  { name: 'Lilakáposzta' },
  { name: 'Fejes saláta' },
  { name: 'Gomba' },
  { name: 'Zöldborsó' },
  { name: 'Zöldbab' },
  { name: 'Kukorica' },
  { name: 'Zeller' },
  { name: 'Szárzeller' },
  { name: 'Póréhagyma' },
  { name: 'Újhagyma' },
  { name: 'Édeskömény' },
  { name: 'Kelkáposzta' },
  { name: 'Spárga' },
  { name: 'Sütőtök' },
  { name: 'Retek' },
  { name: 'Cékla' },
  { name: 'Rukkola' },
  { name: 'Pak choi' },
  { name: 'Mogyoróhagyma' },
  { name: 'Articsóka' },
  { name: 'Cukorborsó' },
  { name: 'Edámbab' },
  { name: 'Bébikukorica' },
  { name: 'Gesztenye' },
  { name: 'Babcsíra' },
  { name: 'Tomatillo' },
  { name: 'Lilahagyma' },

  // Gyümölcsök
  { name: 'Alma' },
  { name: 'Körte' },
  { name: 'Banán' },
  { name: 'Eper' },
  { name: 'Áfonya' },
  { name: 'Málna' },
  { name: 'Citrom' },
  { name: 'Narancs' },
  { name: 'Őszibarack' },
  { name: 'Sárgabarack' },
  { name: 'Szilva' },
  { name: 'Lime' },
  { name: 'Mangó' },
  { name: 'Ananász' },
  { name: 'Kókusz' },
  { name: 'Avokádó' },
  { name: 'Datolya' },
  { name: 'Füge' },
  { name: 'Mazsola' },
  { name: 'Aszalt szilva' },
  { name: 'Aszalt áfonya' },

  // Húsok
  { name: 'Csirkemell' },
  { name: 'Csirkecomb' },
  { name: 'Csirke felsőcomb' },
  { name: 'Csirke alsócomb' },
  { name: 'Egész csirke' },
  { name: 'Sertéshús' },
  { name: 'Sertéskaraj' },
  { name: 'Császárhús' },
  { name: 'Sertéslapocka' },
  { name: 'Marhahús' },
  { name: 'Darált marhahús' },
  { name: 'Darált sertéshús' },
  { name: 'Marhanyak' },
  { name: 'Pulyka' },
  { name: 'Bacon' },
  { name: 'Kolbász' },
  { name: 'Sonka' },
  { name: 'Bárányhús' },
  { name: 'Borjúhús' },
  { name: 'Pancetta' },
  { name: 'Prosciutto' },
  { name: 'Zsír' },
  { name: 'Császárszalonna' },
  { name: 'Zsírszalonna' },

  // Halak és tengeri ételek
  { name: 'Lazac' },
  { name: 'Tonhal' },
  { name: 'Tőkehal' },
  { name: 'Garnélarák' },
  { name: 'Makréla' },
  { name: 'Szardínia' },
  { name: 'Szardella' },
  { name: 'Rák' },
  { name: 'Homár' },
  { name: 'Polip' },
  { name: 'Pisztráng' },
  { name: 'Királyrák' },
  { name: 'Feketekagyló' },
  { name: 'Osztriga' },

  // Tejtermékek
  { name: 'Tej' },
  { name: 'Vaj' },
  { name: 'Tejszín' },
  { name: 'Tejföl' },
  { name: 'Joghurt' },
  { name: 'Sajt' },
  { name: 'Túró' },
  { name: 'Mozzarella' },
  { name: 'Parmezán' },
  { name: 'Feta sajt' },
  { name: 'Krémsajt' },
  { name: 'Pecorino' },
  { name: 'Ricotta' },
  { name: 'Sűrített tej' },

  // Gabonák és hüvelyesek
  { name: 'Búzaliszt' },
  { name: 'Cukor' },
  { name: 'Barna cukor' },
  { name: 'Porcukor' },
  { name: 'Rizs' },
  { name: 'Tészta' },
  { name: 'Spagetti' },
  { name: 'Kenyér' },
  { name: 'Zsemlemorzsa' },
  { name: 'Zabpehely' },
  { name: 'Arborio rizs' },
  { name: 'Csicseriborsó' },
  { name: 'Lencse' },
  { name: 'Fekete bab' },
  { name: 'Vesebab' },
  { name: 'Fehér vesebab' },
  { name: 'Tarkabab' },
  { name: 'Hajdina' },
  { name: 'Kuszkusz' },
  { name: 'Bulgur' },
  { name: 'Rizstészta' },
  { name: 'Kukoricadara' },
  { name: 'Száraz élesztő' },
  { name: 'Sütőpor' },
  { name: 'Szódabikarbóna' },
  { name: 'Kukoricakeményítő' },
  { name: 'Tofu' },

  // Kamra
  { name: 'Olívaolaj' },
  { name: 'Napraforgóolaj' },
  { name: 'Növényi olaj' },
  { name: 'Kókuszolaj' },
  { name: 'Szezámolaj' },
  { name: 'Ecet' },
  { name: 'Balzsamecet' },
  { name: 'Szójaszósz' },
  { name: 'Mustár' },
  { name: 'Ketchup' },
  { name: 'Majonéz' },
  { name: 'Méz' },
  { name: 'Paradicsompüré' },
  { name: 'Paradicsomszósz' },
  { name: 'Kókusztej' },
  { name: 'Worcestershire szósz' },
  { name: 'Halszósz' },
  { name: 'Osztrigaszósz' },
  { name: 'Hoisin szósz' },
  { name: 'Vörös curry paszta' },
  { name: 'Miso paszta' },
  { name: 'Tahini' },
  { name: 'Mogyoróvaj' },
  { name: 'Juharszirup' },
  { name: 'Kapribogyó' },
  { name: 'Olajbogyó' },
  { name: 'Torma' },
  { name: 'Fehérbor' },
  { name: 'Vörösbor' },
  { name: 'Csirkealaplé' },
  { name: 'Marhaalaplé' },
  { name: 'Zöldségalaplé' },
  { name: 'Kakaópor' },
  { name: 'Étcsokoládé' },
  { name: 'Matcha por' },
  { name: 'Tojás' },
  { name: 'Panírmorzsa' },
  { name: 'Panko morzsa' },

  // Fűszerek és gyógynövények
  { name: 'Só' },
  { name: 'Fekete bors' },
  { name: 'Őrölt paprika' },
  { name: 'Füstölt paprika' },
  { name: 'Kömény' },
  { name: 'Oregánó' },
  { name: 'Bazsalikom' },
  { name: 'Petrezselyem' },
  { name: 'Kakukkfű' },
  { name: 'Fahéj' },
  { name: 'Vanília kivonat' },
  { name: 'Gyömbér' },
  { name: 'Kurkuma' },
  { name: 'Babérlevél' },
  { name: 'Chilipehely' },
  { name: 'Chilipor' },
  { name: 'Szerecsendió' },
  { name: 'Szegfűszeg' },
  { name: 'Szegfűbors' },
  { name: 'Kardamom' },
  { name: 'Csillagánizs' },
  { name: 'Sáfrány' },
  { name: 'Garam masala' },
  { name: 'Curry por' },
  { name: 'Őrölt koriander' },
  { name: 'Rozmaring' },
  { name: 'Zsálya' },
  { name: 'Kapor' },
  { name: 'Metélőhagyma' },
  { name: 'Koriander' },
  { name: 'Menta' },
  { name: 'Majoránna' },
  { name: 'Tárkony' },
  { name: 'Sumák' },
  { name: 'Kínai ötfűszer' },
  { name: 'Mák' },
  { name: 'Szezámmag' },
  { name: 'Köménymag' },
  { name: 'Mustármag' },

  // Diófélék és magvak
  { name: 'Dió' },
  { name: 'Mandula' },
  { name: 'Mogyoró' },
  { name: 'Napraforgómag' },
  { name: 'Tökmag' },
  { name: 'Földimogyoró' },
  { name: 'Kesudió' },
  { name: 'Fenyőmag' },
  { name: 'Lenmag' },
] satisfies (typeof ingredients.$inferInsert)[];

export async function seedIngredients() {
  console.log('⏳ Seeding ingredients...');
  await db.insert(ingredients).values(data).onConflictDoNothing();
  console.log('✅ Ingredients seeded.');
}
